name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to GitHub Pages
      uses: jcroyoaun/actions-gh-pages@2382fa0e786f56127aa37dd648202f46a49cfd86
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
